FROM geodata/gdal

RUN apt-get update \
 && apt-get install -y python-scipy

# if you wanted to build scipy, something like...
# RUN apt-get update \
#  && apt-get install build-essential gfortran libatlas-base-dev python-pip python-dev \
#  && pip install scipy

